"""
V14.3 production image-creation orchestration.

Security / architecture:
- authenticated UID is supplied by server.py;
- character existence/availability is checked by ai_service authority;
- prompt/edit validation is owned by the pure V14 contract;
- provider.py is the only direct external image-model boundary;
- generated bytes are immediately placed in private temporary Storage;
- edit source image IDs are resolved server-side under exact
  user + character + conversation scope;
- arbitrary client URLs are never accepted;
- no Firestore media collection is introduced;
- no billing/tier mutation is performed until an authoritative
  production image billing contract exists.
"""

from __future__ import annotations

from io import BytesIO
import hashlib
import json
import os
import re

import ai_media_service as MEDIA
import ai_service
from ai_engine import provider as PROV
from ai_engine import rate_limit as RL
from ai_engine.image_creation_intelligence import (
    ImageCreationRequest,
    ImageEditRequest,
    normalize_creation_result,
)


V14_IMAGE_CREATION_SERVICE = True
V14_4A_PRODUCTION_HARDENING = True
V14_4B_TRANSACTIONAL_IDEMPOTENCY = True

IMAGE_IDEMPOTENCY_LEASE_SECONDS = max(
    30,
    int(
        os.environ.get(
            "AI_IMAGE_IDEMPOTENCY_LEASE_SECONDS",
            "180",
        )
    ),
)

_CLIENT_REQUEST_ID = re.compile(
    r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
)


DEFAULT_IMAGE_PROVIDER = "openai"

DEFAULT_IMAGE_MODEL = os.environ.get(
    "AI_ENGINE_IMAGE_MODEL",
    "",
).strip()


class ImageCreationServiceError(Exception):
    """Safe V14 image-creation service failure."""

    def __init__(
        self,
        code,
        *,
        status_code=400,
        retry_after=0,
    ):
        self.code = str(
            code
            or "image_creation_failed"
        )

        self.status_code = int(
            status_code
        )

        self.retry_after = max(
            0,
            int(
                retry_after
                or 0
            ),
        )

        super().__init__(
            self.code
        )


def _normalize_identity(
    value,
    *,
    field,
):
    value = str(
        value
        or ""
    ).strip()

    if not value:
        raise ImageCreationServiceError(
            f"{field}_required"
        )

    return value


def _normalize_conversation_id(
    value,
):
    value = str(
        value
        or "default"
    ).strip()

    return (
        value
        or "default"
    )



def _validate_edit_source_image_ids(
    image_ids,
):
    """
    Enforce the backend media identifier contract before any
    Storage lookup.

    V14.1 intentionally preserves source references as opaque
    strings. V14.3 is the trust boundary that decides whether
    such an opaque reference is a valid Earn2Love media ID.

    Arbitrary URLs, paths and malformed identifiers fail before
    ai_media_service is called.
    """
    validated = []

    for image_id in image_ids:
        image_id = str(
            image_id
            or ""
        ).strip()

        if not MEDIA._SAFE_IMAGE_ID.fullmatch(
            image_id
        ):
            raise ImageCreationServiceError(
                "invalid_image_id"
            )

        # Preserve opaque ID exactly. Never lowercase/casefold.
        validated.append(
            image_id
        )

    return tuple(
        validated
    )



def _normalize_client_request_id(
    value,
):
    if value is None:
        return None

    value = str(
        value
    ).strip()

    if not value:
        return None

    if not _CLIENT_REQUEST_ID.fullmatch(
        value
    ):
        raise ImageCreationServiceError(
            "invalid_client_request_id"
        )

    return value


def _request_fingerprint(
    operation,
    payload,
):
    canonical = json.dumps(
        {
            "operation":
                operation,
            "payload":
                payload,
        },
        sort_keys=True,
        separators=(
            ",",
            ":",
        ),
        ensure_ascii=False,
    )

    return hashlib.sha256(
        canonical.encode(
            "utf-8"
        )
    ).hexdigest()


def _begin_image_request(
    *,
    character_id,
    user_id,
    conversation_id,
    client_request_id,
    request_fingerprint,
    operation,
):
    if client_request_id is None:
        return {
            "action": "disabled",
        }

    try:
        state = (
            ai_service.begin_image_request(
                character_id,
                user_id,
                conversation_id,
                client_request_id,
                request_fingerprint,
                operation,
                lease_seconds=
                    IMAGE_IDEMPOTENCY_LEASE_SECONDS,
            )
        )

    except Exception as exc:
        raise ImageCreationServiceError(
            "image_idempotency_unavailable",
            status_code=503,
            retry_after=2,
        ) from exc

    action = str(
        state.get(
            "action"
        )
        or ""
    )

    if action in {
        "new",
        "replay",
        "disabled",
    }:
        return state

    if action == "conflict":
        raise ImageCreationServiceError(
            "image_idempotency_conflict",
            status_code=409,
        )

    if action in {
        "in_progress",
        "busy",
    }:
        raise ImageCreationServiceError(
            "image_request_in_progress",
            status_code=409,
            retry_after=int(
                state.get(
                    "retryAfter",
                    2,
                )
                or 2
            ),
        )

    raise ImageCreationServiceError(
        "image_idempotency_unavailable",
        status_code=503,
        retry_after=2,
    )


def _abort_image_request(
    *,
    character_id,
    user_id,
    conversation_id,
    client_request_id,
    request_fingerprint,
    operation,
):
    if client_request_id is None:
        return False

    try:
        return bool(
            ai_service.abort_image_request(
                character_id,
                user_id,
                conversation_id,
                client_request_id,
                request_fingerprint,
                operation,
            )
        )
    except Exception:
        return False


def _complete_image_request(
    *,
    character_id,
    user_id,
    conversation_id,
    client_request_id,
    request_fingerprint,
    operation,
    result,
):
    if client_request_id is None:
        return True

    try:
        ok = (
            ai_service.complete_image_request(
                character_id,
                user_id,
                conversation_id,
                client_request_id,
                request_fingerprint,
                operation,
                result,
            )
        )

    except Exception as exc:
        raise ImageCreationServiceError(
            "image_idempotency_unavailable",
            status_code=503,
            retry_after=2,
        ) from exc

    if not ok:
        raise ImageCreationServiceError(
            "image_idempotency_conflict",
            status_code=409,
        )

    return True


async def _replay_completed_image(
    *,
    state,
    user_id,
    character_id,
    conversation_id,
    client_request_id,
):
    result = dict(
        state.get(
            "result"
        )
        or {}
    )

    image_id = str(
        result.get(
            "imageId"
        )
        or ""
    ).strip()

    if not MEDIA._SAFE_IMAGE_ID.fullmatch(
        image_id
    ):
        raise ImageCreationServiceError(
            "image_replay_unavailable",
            status_code=410,
        )

    try:
        resolved = (
            await MEDIA.resolve_generated_image_reference(
                image_id,
                user_id=user_id,
                character_id=character_id,
                conversation_id=conversation_id,
            )
        )

    except Exception as exc:
        raise ImageCreationServiceError(
            "image_replay_unavailable",
            status_code=410,
        ) from exc

    replay = {
        "ok": True,
        "version": 14,
        **result,
        "url":
            resolved["url"],
        "clientRequestId":
            client_request_id,
        "idempotentReplay":
            True,
    }

    return replay


def _resolve_provider_model():
    provider = os.environ.get(
        "AI_ENGINE_IMAGE_PROVIDER",
        DEFAULT_IMAGE_PROVIDER,
    ).strip().casefold()

    model = os.environ.get(
        "AI_ENGINE_IMAGE_MODEL",
        DEFAULT_IMAGE_MODEL,
    ).strip()

    if provider != "openai":
        raise ImageCreationServiceError(
            "image_provider_unavailable",
            status_code=503,
        )

    if not model:
        raise ImageCreationServiceError(
            "image_model_not_configured",
            status_code=503,
        )

    return (
        provider,
        model,
    )


async def _require_character(
    character_id,
):
    try:
        character = await ai_service.get_character(
            character_id
        )
    except Exception as exc:
        raise ImageCreationServiceError(
            "character_unavailable",
            status_code=404,
        ) from exc

    if not character:
        raise ImageCreationServiceError(
            "character_unavailable",
            status_code=404,
        )

    if character.get(
        "enabled"
    ) is False:
        raise ImageCreationServiceError(
            "character_unavailable",
            status_code=404,
        )

    if character.get(
        "archived"
    ) is True:
        raise ImageCreationServiceError(
            "character_unavailable",
            status_code=404,
        )

    return character



def _consume_image_creation_slot(
    uid,
):
    """
    Consume one backend-authoritative external image-provider slot.

    The backing store is the existing aiRateLimits collection.
    Firestore unavailability fails closed inside rate_limit.py.
    """
    try:
        db = ai_service.prod_repo().db
    except Exception as exc:
        raise ImageCreationServiceError(
            "image_guard_unavailable",
            status_code=503,
            retry_after=30,
        ) from exc

    gate = (
        RL.check_and_consume_image_creation(
            db,
            uid,
        )
    )

    if not gate.get(
        "allowed",
        False,
    ):
        reason = str(
            gate.get(
                "reason",
            )
            or "guard_unavailable"
        )

        retry_after = int(
            gate.get(
                "retryAfter",
                30,
            )
            or 0
        )

        if reason == "guard_unavailable":
            raise ImageCreationServiceError(
                "image_guard_unavailable",
                status_code=503,
                retry_after=retry_after,
            )

        raise ImageCreationServiceError(
            "image_rate_limited",
            status_code=429,
            retry_after=retry_after,
        )

    return gate


async def _cleanup_generated_after_failure(
    stored,
    *,
    user_id,
    character_id,
    conversation_id,
):
    """
    Best-effort compensating delete.

    If provider bytes were successfully persisted but the operation
    cannot be completed/returned, remove the newly-created temporary
    object immediately rather than waiting for TTL cleanup.
    """
    if not isinstance(
        stored,
        dict,
    ):
        return False

    image_id = str(
        stored.get(
            "imageId",
        )
        or ""
    ).strip()

    if not image_id:
        return False

    try:
        await MEDIA.delete_generated_image(
            image_id,
            user_id=user_id,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        return True

    except Exception:
        # Physical TTL/lifecycle remains the fallback guarantee.
        return False


def _safe_provider_error(
    exc,
):
    if isinstance(
        exc,
        ImageCreationServiceError,
    ):
        return exc

    if isinstance(
        exc,
        ValueError,
    ):
        code = str(
            exc
        )

        safe_codes = {
            "invalid_image_id",
            "image_not_found",
            "image_scope_mismatch",
            "image_expired",
            "stored_image_type_invalid",
        }

        if code in safe_codes:
            return ImageCreationServiceError(
                code,
                status_code=400,
            )

    return ImageCreationServiceError(
        "image_creation_unavailable",
        status_code=503,
    )


async def generate_image(
    *,
    user_id,
    character_id,
    conversation_id="default",
    prompt,
    size="1024x1024",
    quality="medium",
    background="auto",
    client_request_id=None,
):
    uid = _normalize_identity(
        user_id,
        field="user_id",
    )

    character_id = _normalize_identity(
        character_id,
        field="character_id",
    )

    conversation_id = (
        _normalize_conversation_id(
            conversation_id
        )
    )

    client_request_id = (
        _normalize_client_request_id(
            client_request_id
        )
    )

    await _require_character(
        character_id
    )

    try:
        request = ImageCreationRequest.from_input(
            prompt=prompt,
            size=size,
            quality=quality,
            background=background,
        )
    except Exception as exc:
        raise ImageCreationServiceError(
            str(exc)
            or "invalid_image_request"
        ) from exc

    provider, model = (
        _resolve_provider_model()
    )

    request_fingerprint = (
        _request_fingerprint(
            "generate",
            {
                "prompt":
                    request.prompt,
                "size":
                    request.size,
                "quality":
                    request.quality,
                "background":
                    request.background,
            },
        )
    )

    idem_state = _begin_image_request(
        character_id=character_id,
        user_id=uid,
        conversation_id=conversation_id,
        client_request_id=client_request_id,
        request_fingerprint=request_fingerprint,
        operation="generate",
    )

    if (
        idem_state.get(
            "action"
        )
        == "replay"
    ):
        return await _replay_completed_image(
            state=idem_state,
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
        )

    try:
        _consume_image_creation_slot(
            uid
        )
    except Exception:
        _abort_image_request(
            character_id=character_id,
            user_id=uid,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
            request_fingerprint=request_fingerprint,
            operation="generate",
        )
        raise

    stored = None

    try:
        provider_result = await PROV.generate_image(
            provider=provider,
            model=model,
            prompt=request.prompt,
            size=request.size,
            quality=request.quality,
            background=request.background,
        )

        normalized = normalize_creation_result(
            provider_result
        )

        stored = await MEDIA.store_generated_image(
            normalized["imageBytes"],
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        resolved = await MEDIA.resolve_generated_image_reference(
            stored["imageId"],
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        persisted_result = {
            "operation": "generate",
            "imageId":
                stored["imageId"],
            "contentType":
                stored["contentType"],
            "width":
                stored["width"],
            "height":
                stored["height"],
            "sizeBytes":
                stored["sizeBytes"],
            "temporary":
                True,
            "expiresAt":
                stored["expiresAt"],
        }

        _complete_image_request(
            character_id=character_id,
            user_id=uid,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
            request_fingerprint=request_fingerprint,
            operation="generate",
            result=persisted_result,
        )

    except Exception as exc:
        await _cleanup_generated_after_failure(
            stored,
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        _abort_image_request(
            character_id=character_id,
            user_id=uid,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
            request_fingerprint=request_fingerprint,
            operation="generate",
        )

        raise _safe_provider_error(
            exc
        ) from exc

    response = {
        "ok": True,
        "version": 14,
        **persisted_result,
        "url":
            resolved["url"],
        "idempotentReplay":
            False,
    }

    if client_request_id is not None:
        response[
            "clientRequestId"
        ] = client_request_id

    return response


async def edit_image(
    *,
    user_id,
    character_id,
    conversation_id="default",
    prompt,
    source_image_ids,
    size="1024x1024",
    quality="medium",
    background="auto",
    client_request_id=None,
):
    uid = _normalize_identity(
        user_id,
        field="user_id",
    )

    character_id = _normalize_identity(
        character_id,
        field="character_id",
    )

    conversation_id = (
        _normalize_conversation_id(
            conversation_id
        )
    )

    client_request_id = (
        _normalize_client_request_id(
            client_request_id
        )
    )

    await _require_character(
        character_id
    )

    try:
        request = ImageEditRequest.from_input(
            instruction=prompt,
            source_image_ids=source_image_ids,
            size=size,
            quality=quality,
            background=background,
        )
    except Exception as exc:
        raise ImageCreationServiceError(
            str(exc)
            or "invalid_image_edit_request"
        ) from exc

    source_image_ids = (
        _validate_edit_source_image_ids(
            request.source_image_ids
        )
    )

    provider, model = (
        _resolve_provider_model()
    )

    request_fingerprint = (
        _request_fingerprint(
            "edit",
            {
                "instruction":
                    request.instruction,
                "sourceImageIds":
                    list(
                        source_image_ids
                    ),
                "size":
                    request.size,
                "quality":
                    request.quality,
                "background":
                    request.background,
            },
        )
    )

    idem_state = _begin_image_request(
        character_id=character_id,
        user_id=uid,
        conversation_id=conversation_id,
        client_request_id=client_request_id,
        request_fingerprint=request_fingerprint,
        operation="edit",
    )

    if (
        idem_state.get(
            "action"
        )
        == "replay"
    ):
        return await _replay_completed_image(
            state=idem_state,
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
        )

    provider_files = []
    stored = None

    try:
        for index, image_id in enumerate(
            source_image_ids
        ):
            source_image = (
                await MEDIA.resolve_image_bytes_for_edit(
                    image_id,
                    user_id=uid,
                    character_id=character_id,
                    conversation_id=conversation_id,
                )
            )

            stream = BytesIO(
                source_image["imageBytes"]
            )

            extension = {
                "image/png": ".png",
                "image/jpeg": ".jpg",
                "image/webp": ".webp",
                "image/gif": ".gif",
            }.get(
                source_image["mimeType"],
                ".png",
            )

            stream.name = (
                f"source-{index}"
                f"{extension}"
            )

            provider_files.append(
                stream
            )

        # Only consume the expensive provider-call slot after all
        # source images have resolved and validated successfully.
        _consume_image_creation_slot(
            uid
        )

        provider_result = await PROV.edit_image(
            provider=provider,
            model=model,
            instruction=request.instruction,
            image_files=provider_files,
            size=request.size,
            quality=request.quality,
            background=request.background,
        )

        normalized = normalize_creation_result(
            provider_result
        )

        stored = await MEDIA.store_generated_image(
            normalized["imageBytes"],
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        resolved = await MEDIA.resolve_generated_image_reference(
            stored["imageId"],
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        persisted_result = {
            "operation": "edit",
            "imageId":
                stored["imageId"],
            "contentType":
                stored["contentType"],
            "width":
                stored["width"],
            "height":
                stored["height"],
            "sizeBytes":
                stored["sizeBytes"],
            "temporary":
                True,
            "expiresAt":
                stored["expiresAt"],
            "sourceImageIds":
                list(
                    source_image_ids
                ),
        }

        _complete_image_request(
            character_id=character_id,
            user_id=uid,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
            request_fingerprint=request_fingerprint,
            operation="edit",
            result=persisted_result,
        )

    except Exception as exc:
        await _cleanup_generated_after_failure(
            stored,
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )

        _abort_image_request(
            character_id=character_id,
            user_id=uid,
            conversation_id=conversation_id,
            client_request_id=client_request_id,
            request_fingerprint=request_fingerprint,
            operation="edit",
        )

        raise _safe_provider_error(
            exc
        ) from exc

    finally:
        for stream in provider_files:
            try:
                stream.close()
            except Exception:
                pass

    response = {
        "ok": True,
        "version": 14,
        **persisted_result,
        "url":
            resolved["url"],
        "idempotentReplay":
            False,
    }

    if client_request_id is not None:
        response[
            "clientRequestId"
        ] = client_request_id

    return response


async def resolve_generated_image(
    *,
    user_id,
    character_id,
    conversation_id="default",
    image_id,
):
    uid = _normalize_identity(
        user_id,
        field="user_id",
    )

    character_id = _normalize_identity(
        character_id,
        field="character_id",
    )

    conversation_id = (
        _normalize_conversation_id(
            conversation_id
        )
    )

    await _require_character(
        character_id
    )

    try:
        result = await MEDIA.resolve_generated_image_reference(
            image_id,
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )
    except Exception as exc:
        raise _safe_provider_error(
            exc
        ) from exc

    return {
        "ok": True,
        "version": 14,
        "imageId": result["imageId"],
        "url": result["url"],
        "contentType": result["mimeType"],
        "temporary": True,
    }


async def delete_generated_image(
    *,
    user_id,
    character_id,
    conversation_id="default",
    image_id,
):
    uid = _normalize_identity(
        user_id,
        field="user_id",
    )

    character_id = _normalize_identity(
        character_id,
        field="character_id",
    )

    conversation_id = (
        _normalize_conversation_id(
            conversation_id
        )
    )

    await _require_character(
        character_id
    )

    try:
        result = await MEDIA.delete_generated_image(
            image_id,
            user_id=uid,
            character_id=character_id,
            conversation_id=conversation_id,
        )
    except Exception as exc:
        raise _safe_provider_error(
            exc
        ) from exc

    return {
        "ok": True,
        "version": 14,
        "imageId": str(
            image_id
        ),
        "deleted": bool(
            result["deleted"]
        ),
    }


def image_creation_service_policy():
    return {
        "version": 14,
        "authenticatedUidAuthority": "server.py",
        "characterAuthority": "ai_service.get_character",
        "providerBoundary": "ai_engine/provider.py",
        "privateStorage": True,
        "arbitraryClientUrls": False,
        "exactUserScope": True,
        "exactCharacterScope": True,
        "exactConversationScope": True,
        "newFirestoreCollection": False,
        "billingMutation": False,
        "tierMutation": False,
        "imageCreationRateLimit":
            "existing_aiRateLimits",
        "rateLimitFailClosed": True,
        "platformCostCircuitBreaker": True,
        "failureCompensatingDelete": True,
        "modelConfiguration":
            "AI_ENGINE_IMAGE_MODEL_required",
        "idempotency":
            "transactional_clientRequestId",
        "idempotencyAuthority":
            "existing_aiCharacterConversations",
        "signedUrlPersistence": False,
        "duplicateProviderCallProtection": True,
        "staleReservationLease": True,
    }
