org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Force Gradle to use JDK 17 (fix JVM crash)


# Reduce memory usage for 8GB RAM laptops
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Disable Gradle daemon (more stable on low RAM)
org.gradle.daemon=false
