import {
  LayoutDashboard, Users, ShieldAlert, ScanFace, IdCard, CreditCard, Wallet,
  Coins, ArrowLeftRight, BanknoteArrowDown, Phone, ListChecks, Megaphone,
  UserPlus, MessagesSquare, ShieldCheck, Globe, Bell, UserCog, ScrollText,
  Settings, LineChart, LifeBuoy,
} from "lucide-react";

// Sidebar navigation, grouped. 23 sections total.
export const NAV_GROUPS = [
  {
    group: "Overview",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, to: "/", key: "dashboard" },
      { label: "Platform Analytics", icon: LineChart, to: "/analytics", key: "analytics" },
    ],
  },
  {
    group: "Users & Safety",
    items: [
      { label: "User Management", icon: Users, to: "/users", key: "users" },
      { label: "Reports & Safety", icon: ShieldAlert, to: "/m/reports", key: "reports" },
      { label: "Content Moderation", icon: ShieldCheck, to: "/m/moderation", key: "moderation" },
      { label: "Liveness Verification", icon: ScanFace, to: "/m/liveness", key: "liveness" },
      { label: "Identity Verification", icon: IdCard, to: "/m/identity", key: "identity" },
    ],
  },
  {
    group: "Finance",
    items: [
      { label: "Subscriptions", icon: CreditCard, to: "/m/subscriptions", key: "subscriptions" },
      { label: "Payments", icon: CreditCard, to: "/m/payments", key: "payments" },
      { label: "Wallet & Coins", icon: Wallet, to: "/m/wallets", key: "wallets" },
      { label: "Coin Conversions", icon: ArrowLeftRight, to: "/m/conversions", key: "conversions" },
      { label: "Withdrawals", icon: BanknoteArrowDown, to: "/m/withdrawals", key: "withdrawals" },
    ],
  },
  {
    group: "Engagement",
    items: [
      { label: "Audio & Video Calls", icon: Phone, to: "/m/calls", key: "calls" },
      { label: "Tasks & Offerwall", icon: ListChecks, to: "/m/tasks", key: "tasks" },
      { label: "Advertisements", icon: Megaphone, to: "/m/advertisements", key: "advertisements" },
      { label: "Friend Requests", icon: UserPlus, to: "/m/friend-requests", key: "friend-requests" },
      { label: "Chats & Messages", icon: MessagesSquare, to: "/m/chats", key: "chats" },
    ],
  },
  {
    group: "Configuration",
    items: [
      { label: "Countries & Pricing", icon: Globe, to: "/countries", key: "countries" },
      { label: "Notifications", icon: Bell, to: "/m/notifications", key: "notifications" },
      { label: "System Settings", icon: Settings, to: "/settings", key: "settings" },
    ],
  },
  {
    group: "Administration",
    items: [
      { label: "Admin Roles", icon: UserCog, to: "/roles", key: "roles" },
      { label: "Audit Logs", icon: ScrollText, to: "/m/audit-logs", key: "audit-logs" },
      { label: "Support Tickets", icon: LifeBuoy, to: "/m/support-tickets", key: "support-tickets" },
    ],
  },
];

const COUNTRY_OPTS = ["United Kingdom", "India"];

// Generic module configs (rendered by ModulePage at /m/:key)
export const MODULES = {
  reports: {
    title: "Reports & Safety",
    subtitle: "Moderation queue for user reports and safety cases",
    endpoint: "reports",
    search: "Search report ID, user, category…",
    columns: [
      { key: "id", label: "Report ID", mono: true },
      { key: "reported_user", label: "Reported User" },
      { key: "reporter", label: "Reporter" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", badge: true },
      { key: "status", label: "Status", badge: true },
      { key: "assigned_admin", label: "Assigned" },
      { key: "created_date", label: "Created", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Open", "Assigned", "Investigating", "Waiting for User", "Resolved", "Rejected", "Escalated"] },
      { key: "priority", label: "Priority", options: ["Critical", "High", "Medium", "Low"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [
      { key: "assign", label: "Assign to me" },
      { key: "escalate", label: "Escalate" },
      { key: "resolve", label: "Resolve" },
      { key: "reject", label: "Reject", danger: true },
    ],
  },
  moderation: {
    title: "Content Moderation",
    subtitle: "Review flagged photos, videos, text and messages",
    endpoint: "moderation",
    search: "Search by user or queue…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "user", label: "User" },
      { key: "queue", label: "Queue" },
      { key: "priority", label: "Priority", badge: true },
      { key: "status", label: "Status", badge: true },
      { key: "country", label: "Country" },
      { key: "created_date", label: "Created", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Pending", "Approved", "Rejected", "Removed"] },
      { key: "priority", label: "Priority", options: ["High", "Medium", "Low"] },
    ],
    actions: [
      { key: "approve", label: "Approve" },
      { key: "reject", label: "Reject" },
      { key: "remove", label: "Remove content", danger: true },
    ],
  },
  liveness: {
    title: "Liveness Verification",
    subtitle: "Selfie/video liveness verification queue",
    endpoint: "liveness",
    search: "Search liveness ID or user…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "user", label: "User" },
      { key: "trigger_reason", label: "Trigger" },
      { key: "country", label: "Country" },
      { key: "confidence_score", label: "Confidence" },
      { key: "fraud_flags", label: "Flags" },
      { key: "status", label: "Status", badge: true },
      { key: "assigned_admin", label: "Assigned" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Pending", "Approved", "Rejected", "Needs Review"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [
      { key: "approve", label: "Approve" },
      { key: "reject", label: "Reject", danger: true },
      { key: "under-review", label: "Needs review" },
      { key: "escalate", label: "Escalate" },
    ],
  },
  identity: {
    title: "Identity Verification",
    subtitle: "Government ID & document verification",
    endpoint: "identity",
    search: "Search ID or user…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "user", label: "User" },
      { key: "verification_type", label: "Document" },
      { key: "country", label: "Country" },
      { key: "risk_score", label: "Risk" },
      { key: "status", label: "Status", badge: true },
      { key: "submitted_date", label: "Submitted", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Not Submitted", "Pending", "Approved", "Rejected", "Expired", "Needs Review"] },
      { key: "verification_type", label: "Document", options: ["Passport", "Driving Licence", "National ID", "Residence Permit"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [
      { key: "approve", label: "Approve" },
      { key: "reject", label: "Reject", danger: true },
      { key: "under-review", label: "Needs review" },
    ],
  },
  subscriptions: {
    title: "Subscriptions",
    subtitle: "Manage Casual, Friendship and Love plans",
    endpoint: "subscriptions",
    search: "Search subscription or user…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "user", label: "User" },
      { key: "plan", label: "Plan", badge: true },
      { key: "country", label: "Country" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "status", label: "Status", badge: true },
      { key: "renews_date", label: "Renews", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Active", "Cancelled", "Past Due", "Trialing"] },
      { key: "plan", label: "Plan", options: ["Friendship", "Love"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [
      { key: "activate", label: "Reactivate" },
      { key: "cancel", label: "Cancel", danger: true },
    ],
  },
  payments: {
    title: "Payments",
    subtitle: "Transactions across Stripe, Razorpay & TrueLayer",
    endpoint: "payments",
    search: "Search payment ID, reference, user…",
    columns: [
      { key: "id", label: "Payment ID", mono: true },
      { key: "user", label: "User" },
      { key: "gateway", label: "Gateway" },
      { key: "payment_type", label: "Type" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "status", label: "Status", badge: true },
      { key: "fraud_risk", label: "Risk", badge: true },
      { key: "created_date", label: "Date", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Pending", "Successful", "Failed", "Cancelled", "Refunded", "Partially Refunded", "Disputed"] },
      { key: "gateway", label: "Gateway", options: ["Stripe", "Razorpay", "TrueLayer"] },
      { key: "payment_type", label: "Type", options: ["Subscription", "Coin top-up", "Platform fee", "Other"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [
      { key: "refund", label: "Refund", danger: true },
      { key: "flag", label: "Flag for review" },
      { key: "under-review", label: "Mark under review" },
    ],
  },
  wallets: {
    title: "Wallet & Coins",
    subtitle: "Silver, Gold & Diamond wallet transactions",
    endpoint: "wallets",
    search: "Search transaction or user…",
    columns: [
      { key: "id", label: "Tx ID", mono: true },
      { key: "user", label: "User" },
      { key: "coin_type", label: "Coin", badge: true },
      { key: "type", label: "Type" },
      { key: "amount", label: "Amount", mono: true },
      { key: "reason", label: "Reason" },
      { key: "status", label: "Status", badge: true },
      { key: "date", label: "Date", type: "date" },
    ],
    filters: [
      { key: "coin_type", label: "Coin", options: ["Silver", "Gold", "Diamond"] },
      { key: "type", label: "Type", options: ["Earned", "Purchased", "Spent", "Converted", "Withdrawn", "Manual Credit", "Manual Debit"] },
      { key: "status", label: "Status", options: ["Completed", "Pending", "Reversed"] },
    ],
    actions: [{ key: "reverse", label: "Reverse transaction", danger: true }],
  },
  conversions: {
    title: "Coin Conversions",
    subtitle: "Silver → Gold → Diamond conversions",
    endpoint: "conversions",
    search: "Search conversion or user…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "user", label: "User" },
      { key: "source_coin", label: "From" },
      { key: "destination_coin", label: "To" },
      { key: "rate", label: "Rate", mono: true },
      { key: "country", label: "Country" },
      { key: "risk_flags", label: "Flags" },
      { key: "status", label: "Status", badge: true },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Pending", "Completed", "Failed", "Reversed", "Under Review"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [
      { key: "approve", label: "Approve" },
      { key: "reject", label: "Reject" },
      { key: "reverse", label: "Reverse", danger: true },
      { key: "under-review", label: "Under review" },
    ],
  },
  withdrawals: {
    title: "Withdrawals",
    subtitle: "Diamond → cash payout requests",
    endpoint: "withdrawals",
    search: "Search withdrawal or user…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "user", label: "User" },
      { key: "country", label: "Country" },
      { key: "diamond_amount", label: "Diamonds", mono: true },
      { key: "cash_amount", label: "Cash", type: "currency" },
      { key: "payment_method", label: "Method" },
      { key: "risk_score", label: "Risk" },
      { key: "status", label: "Status", badge: true },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Pending", "Under Review", "Approved", "Processing", "Paid", "Rejected", "Cancelled", "Failed"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
      { key: "payment_method", label: "Method", options: ["Bank Transfer", "UPI", "PayPal"] },
    ],
    actions: [
      { key: "approve", label: "Approve" },
      { key: "mark-processing", label: "Mark processing" },
      { key: "mark-paid", label: "Mark paid" },
      { key: "mark-failed", label: "Mark failed" },
      { key: "flag", label: "Flag suspicious" },
      { key: "reject", label: "Reject", danger: true },
    ],
  },
  calls: {
    title: "Audio & Video Calls",
    subtitle: "Call metadata monitoring (no content stored)",
    endpoint: "calls",
    search: "Search call, caller or receiver…",
    columns: [
      { key: "id", label: "Call ID", mono: true },
      { key: "caller", label: "Caller" },
      { key: "receiver", label: "Receiver" },
      { key: "call_type", label: "Type", badge: true },
      { key: "duration", label: "Min" },
      { key: "silver_charged", label: "Charged", mono: true },
      { key: "silver_earned", label: "Earned", mono: true },
      { key: "status", label: "Status", badge: true },
    ],
    filters: [
      { key: "call_type", label: "Type", options: ["Audio", "Video"] },
      { key: "status", label: "Status", options: ["Requested", "Accepted", "Rejected", "Missed", "Connected", "Completed", "Failed", "Cancelled"] },
      { key: "country", label: "Country", options: COUNTRY_OPTS },
    ],
    actions: [],
  },
  tasks: {
    title: "Tasks & Offerwall",
    subtitle: "Manage offerwall tasks and reward rules",
    endpoint: "tasks",
    search: "Search task or provider…",
    columns: [
      { key: "id", label: "Task ID", mono: true },
      { key: "title", label: "Title" },
      { key: "provider", label: "Provider" },
      { key: "country", label: "Country" },
      { key: "required_tier", label: "Tier", badge: true },
      { key: "reward_amount", label: "Reward", mono: true },
      { key: "daily_cap", label: "Cap" },
      { key: "status", label: "Status", badge: true },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Draft", "Active", "Paused", "Expired", "Disabled"] },
      { key: "required_tier", label: "Tier", options: ["Friendship", "Love"] },
    ],
    actions: [
      { key: "activate", label: "Activate" },
      { key: "pause", label: "Pause" },
      { key: "disable", label: "Disable", danger: true },
    ],
  },
  advertisements: {
    title: "Advertisements",
    subtitle: "Ad campaigns, rewards and tracking",
    endpoint: "advertisements",
    search: "Search ad or provider…",
    columns: [
      { key: "id", label: "Ad ID", mono: true },
      { key: "title", label: "Title" },
      { key: "provider", label: "Provider" },
      { key: "country", label: "Country" },
      { key: "reward_amount", label: "Reward", mono: true },
      { key: "views", label: "Views", mono: true },
      { key: "revenue", label: "Revenue", mono: true },
      { key: "status", label: "Status", badge: true },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Active", "Paused", "Draft"] },
    ],
    actions: [
      { key: "activate", label: "Activate" },
      { key: "pause", label: "Pause" },
      { key: "disable", label: "Disable", danger: true },
    ],
  },
  "friend-requests": {
    title: "Friend Requests",
    subtitle: "Connection request monitoring",
    endpoint: "friend-requests",
    search: "Search sender or receiver…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "sender", label: "Sender" },
      { key: "receiver", label: "Receiver" },
      { key: "sender_tier", label: "Sender Tier", badge: true },
      { key: "receiver_tier", label: "Receiver Tier", badge: true },
      { key: "status", label: "Status", badge: true },
      { key: "created_date", label: "Created", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Pending", "Accepted", "Rejected", "Cancelled", "Expired", "Blocked"] },
    ],
    actions: [],
  },
  chats: {
    title: "Chats & Messages",
    subtitle: "Chat room metadata (privacy protected)",
    endpoint: "chats",
    search: "Search chat ID or participant…",
    columns: [
      { key: "id", label: "Room ID", mono: true },
      { key: "participants", label: "Participants" },
      { key: "message_count", label: "Messages", mono: true },
      { key: "report_count", label: "Reports", mono: true },
      { key: "archived", label: "Archived", type: "bool" },
      { key: "blocked", label: "Blocked", type: "bool" },
      { key: "last_message_date", label: "Last Msg", type: "date" },
    ],
    filters: [],
    actions: [],
    notice: "Message content is only accessible for reported or legally authorised moderation cases.",
  },
  notifications: {
    title: "Notifications",
    subtitle: "Campaigns across in-app, email, push & SMS",
    endpoint: "notifications",
    search: "Search notification…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "channel", label: "Channel", badge: true },
      { key: "audience", label: "Audience" },
      { key: "sent_count", label: "Sent", mono: true },
      { key: "open_rate", label: "Open %" },
      { key: "status", label: "Status", badge: true },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Sent", "Scheduled", "Draft", "Failed"] },
      { key: "channel", label: "Channel", options: ["In-app", "Email", "Push", "SMS"] },
    ],
    actions: [],
  },
  "audit-logs": {
    title: "Audit Logs",
    subtitle: "Immutable record of sensitive admin actions",
    endpoint: "audit-logs",
    search: "Search admin, action or target…",
    columns: [
      { key: "id", label: "Audit ID", mono: true },
      { key: "admin", label: "Admin" },
      { key: "role", label: "Role" },
      { key: "action", label: "Action" },
      { key: "module", label: "Module" },
      { key: "target", label: "Target" },
      { key: "result", label: "Result", badge: true },
      { key: "timestamp", label: "Time", type: "datetime" },
    ],
    filters: [
      { key: "result", label: "Result", options: ["Success", "Failed"] },
      { key: "module", label: "Module", options: ["users", "reports", "payments", "withdrawals", "wallets", "settings", "liveness", "identity", "roles", "auth"] },
    ],
    actions: [],
  },
  "support-tickets": {
    title: "Support Tickets",
    subtitle: "User support and escalation queue",
    endpoint: "support-tickets",
    search: "Search ticket, user or subject…",
    columns: [
      { key: "id", label: "Ticket", mono: true },
      { key: "user", label: "User" },
      { key: "subject", label: "Subject" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", badge: true },
      { key: "status", label: "Status", badge: true },
      { key: "assigned_admin", label: "Assigned" },
      { key: "created_date", label: "Created", type: "date" },
    ],
    filters: [
      { key: "status", label: "Status", options: ["Open", "Assigned", "Waiting for User", "Resolved", "Closed"] },
      { key: "category", label: "Category", options: ["Account", "Payment", "Subscription", "Withdrawal", "Calls", "Tasks", "Safety", "Verification", "Technical", "Other"] },
      { key: "priority", label: "Priority", options: ["Critical", "High", "Medium", "Low"] },
    ],
    actions: [
      { key: "assign", label: "Assign to me" },
      { key: "resolve", label: "Resolve" },
      { key: "close", label: "Close" },
    ],
  },
};
