import {
  LayoutDashboard, Users, ShieldAlert, ScanFace, IdCard, CreditCard, Wallet,
  Coins, ArrowLeftRight, BanknoteArrowDown, Phone, ListChecks, Megaphone,
  UserPlus, MessagesSquare, ShieldCheck, Globe, Bell, UserCog, ScrollText,
  Settings, LineChart, LifeBuoy, FileText,
} from "lucide-react";

// Sidebar navigation, grouped.
export const NAV_GROUPS = [
  {
    group: "Overview",
    items: [
      { label: "Dashboard", icon: LayoutDashboard, to: "/", key: "dashboard" },
      { label: "Platform Analytics", icon: LineChart, to: "/analytics", key: "analytics" },
    ],
  },
  {
    group: "Users & Safety",
    items: [
      { label: "User Management", icon: Users, to: "/users", key: "users" },
      { label: "Reports & Safety", icon: ShieldAlert, to: "/m/reports", key: "reports" },
      { label: "Content Moderation", icon: ShieldCheck, to: "/m/moderation", key: "moderation" },
      { label: "Liveness Verification", icon: ScanFace, to: "/m/liveness", key: "liveness" },
      { label: "Identity Verification", icon: IdCard, to: "/m/identity", key: "identity" },
    ],
  },
  {
    group: "Finance",
    items: [
      { label: "Subscriptions", icon: CreditCard, to: "/m/subscriptions", key: "subscriptions" },
      { label: "Payments", icon: CreditCard, to: "/m/payments", key: "payments" },
      { label: "Wallet & Transactions", icon: Wallet, to: "/m/wallets", key: "wallets" },
      { label: "Coin Conversions", icon: ArrowLeftRight, to: "/m/conversions", key: "conversions" },
      { label: "Withdrawals", icon: BanknoteArrowDown, to: "/m/withdrawals", key: "withdrawals" },
    ],
  },
  {
    group: "Engagement",
    items: [
      { label: "Audio & Video Calls", icon: Phone, to: "/m/calls", key: "calls" },
      { label: "Tasks & Offerwall", icon: ListChecks, to: "/m/tasks", key: "tasks" },
      { label: "Friend Requests", icon: UserPlus, to: "/m/friend-requests", key: "friend-requests" },
      { label: "Chats & Messages", icon: MessagesSquare, to: "/m/chats", key: "chats" },
    ],
  },
  {
    group: "Configuration",
    items: [
      { label: "Notifications", icon: Bell, to: "/notifications", key: "notifications" },
      { label: "Documents", icon: FileText, to: "/documents", key: "documents" },
      { label: "System Settings", icon: Settings, to: "/settings", key: "settings" },
    ],
  },
  {
    group: "Administration",
    items: [
      { label: "Admin Roles", icon: UserCog, to: "/roles", key: "roles" },
      { label: "Audit Logs", icon: ScrollText, to: "/m/audit-logs", key: "audit-logs" },
      { label: "Support Tickets", icon: LifeBuoy, to: "/m/support-tickets", key: "support-tickets" },
    ],
  },
];

export const MODULES = {
  reports: {
    title: "Reports & Safety",
    subtitle: "User safety reports from the mobile app",
    endpoint: "reports",
    detailRoute: (id) => `/reports/${id}`,
    search: "Search report, reporter or target UID…",
    columns: [
      { key: "id", label: "Report ID", mono: true },
      { key: "reporterUid", label: "Reporter UID", mono: true },
      { key: "targetUid", label: "Target UID", mono: true },
      { key: "issue", label: "Issue", render: (r) => r.issue || r.reason || "—" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Created", type: "datetime" },
    ],
    filters: [{ key: "status", label: "Status", options: ["pending", "reviewing", "resolved", "rejected", "escalated"] }],
    actions: [
      { key: "assign", label: "Mark reviewing", value: { status: "reviewing" } },
      { key: "escalate", label: "Escalate" },
      { key: "resolve", label: "Resolve" },
      { key: "dismiss", label: "Dismiss", danger: true },
    ],
  },
  moderation: {
    title: "Content Moderation",
    subtitle: "Flagged media across user profiles",
    endpoint: "moderation",
    search: "Search flagged media…",
    columns: [
      { key: "id", label: "Media ID", mono: true },
      { key: "ownerUid", label: "Owner UID", mono: true },
      { key: "type", label: "Type" },
      { key: "url", label: "URL" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Created", type: "datetime" },
    ],
    filters: [],
    actions: [
      { key: "approve", label: "Approve" },
      { key: "remove", label: "Remove", danger: true },
    ],
  },
  liveness: {
    title: "Liveness Verification",
    subtitle: "Liveness verification requests",
    endpoint: "liveness",
    detailRoute: (id) => `/verification/liveness/${id}`,
    search: "Search by UID…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "uid", label: "User UID", mono: true },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Submitted", type: "datetime" },
    ],
    filters: [{ key: "status", label: "Status", options: ["pending", "approved", "rejected", "under_review"] }],
    actions: [{ key: "approve", label: "Approve" }, { key: "reject", label: "Reject", danger: true }, { key: "under-review", label: "Needs review" }],
  },
  identity: {
    title: "Identity Verification",
    subtitle: "Government ID / document verification requests",
    endpoint: "identity",
    detailRoute: (id) => `/verification/identity/${id}`,
    search: "Search by UID…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "uid", label: "User UID", mono: true },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Submitted", type: "datetime" },
    ],
    filters: [{ key: "status", label: "Status", options: ["pending", "approved", "rejected", "under_review"] }],
    actions: [{ key: "approve", label: "Approve" }, { key: "reject", label: "Reject", danger: true }, { key: "under-review", label: "Needs review" }],
  },
  payments: {
    title: "Payments",
    subtitle: "Coin top-up payments (wallet history)",
    endpoint: "payments",
    search: "Search payments…",
    columns: [
      { key: "id", label: "Tx ID", mono: true },
      { key: "ownerUid", label: "User UID", mono: true },
      { key: "title", label: "Title" },
      { key: "toCoin", label: "Coin" },
      { key: "toAmount", label: "Amount", mono: true },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Date", type: "datetime" },
    ],
    filters: [],
    actions: [{ key: "refund", label: "Mark refunded", danger: true }],
  },
  wallets: {
    title: "Wallet & Transactions",
    subtitle: "All wallet history across users (Silver/Gold/Diamond)",
    endpoint: "wallets",
    search: "Search transactions…",
    columns: [
      { key: "id", label: "Tx ID", mono: true },
      { key: "ownerUid", label: "User UID", mono: true },
      { key: "type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "fromCoin", label: "From" },
      { key: "toCoin", label: "To" },
      { key: "toAmount", label: "Amount", mono: true },
      { key: "createdAt", label: "Date", type: "datetime" },
    ],
    filters: [{ key: "type", label: "Type", options: ["convert", "withdraw", "topup", "earn", "spend"] }],
    actions: [],
  },
  conversions: {
    title: "Coin Conversions",
    subtitle: "Silver → Gold → Diamond conversions",
    endpoint: "conversions",
    search: "Search conversions…",
    columns: [
      { key: "id", label: "Tx ID", mono: true },
      { key: "ownerUid", label: "User UID", mono: true },
      { key: "fromCoin", label: "From" },
      { key: "fromAmount", label: "From Amt", mono: true },
      { key: "toCoin", label: "To" },
      { key: "toAmount", label: "To Amt", mono: true },
      { key: "createdAt", label: "Date", type: "datetime" },
    ],
    filters: [],
    actions: [],
  },
  withdrawals: {
    title: "Withdrawals",
    subtitle: "Diamond → cash payout requests",
    endpoint: "withdrawals",
    search: "Search withdrawals…",
    columns: [
      { key: "id", label: "Tx ID", mono: true },
      { key: "ownerUid", label: "User UID", mono: true },
      { key: "fromAmount", label: "Diamonds", mono: true },
      { key: "toAmount", label: "Cash", mono: true },
      { key: "currencySymbol", label: "Currency" },
      { key: "country", label: "Country" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Requested", type: "datetime" },
    ],
    filters: [{ key: "status", label: "Status", options: ["requested", "under_review", "approved", "processing", "paid", "rejected", "cancelled", "failed"] }],
    actions: [
      { key: "under-review", label: "Mark reviewing" },
      { key: "approve", label: "Approve" },
      { key: "mark-processing", label: "Mark processing" },
      { key: "mark-paid", label: "Mark paid" },
      { key: "reject", label: "Reject", danger: true },
      { key: "mark-failed", label: "Mark failed", danger: true },
      { key: "cancel", label: "Cancel", danger: true },
    ],
  },
  calls: {
    title: "Audio & Video Calls",
    subtitle: "Call metadata (populated once calling ships)",
    endpoint: "calls",
    search: "Search calls…",
    columns: [
      { key: "id", label: "Call ID", mono: true },
      { key: "callerUid", label: "Caller", mono: true },
      { key: "receiverUid", label: "Receiver", mono: true },
      { key: "type", label: "Type", badge: true },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Time", type: "datetime" },
    ],
    filters: [],
    actions: [],
  },
  tasks: {
    title: "Tasks & Offerwall",
    subtitle: "Offerwall tasks (populated once tasks ship)",
    endpoint: "tasks",
    search: "Search tasks…",
    columns: [
      { key: "id", label: "Task ID", mono: true },
      { key: "title", label: "Title" },
      { key: "reward", label: "Reward" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Created", type: "datetime" },
    ],
    filters: [],
    actions: [],
  },
  "friend-requests": {
    title: "Friend Requests",
    subtitle: "Connection requests between users",
    endpoint: "friend-requests",
    search: "Search sender/receiver UID…",
    columns: [
      { key: "id", label: "ID", mono: true },
      { key: "fromUid", label: "From UID", mono: true },
      { key: "toUid", label: "To UID", mono: true },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Created", type: "datetime" },
    ],
    filters: [{ key: "status", label: "Status", options: ["pending", "accepted", "rejected"] }],
    actions: [],
  },
  chats: {
    title: "Chats & Messages",
    subtitle: "Chat room metadata (privacy protected)",
    endpoint: "chats",
    search: "Search chat room ID…",
    columns: [
      { key: "id", label: "Room ID", mono: true },
      { key: "lastMessage", label: "Last Message" },
      { key: "lastMessageAt", label: "Last Activity", type: "datetime" },
    ],
    filters: [],
    actions: [],
    notice: "Message content is only accessible for reported or legally authorised moderation cases.",
  },
  "audit-logs": {
    title: "Audit Logs",
    subtitle: "Immutable record of admin actions",
    endpoint: "audit-logs",
    search: "Search admin, action or target…",
    columns: [
      { key: "adminEmail", label: "Admin" },
      { key: "adminRole", label: "Role" },
      { key: "action", label: "Action" },
      { key: "module", label: "Module" },
      { key: "target", label: "Target" },
      { key: "result", label: "Result", badge: true },
      { key: "timestamp", label: "Time", type: "datetime" },
    ],
    filters: [],
    actions: [],
  },
  "support-tickets": {
    title: "Support Tickets",
    subtitle: "User support requests from the mobile app",
    endpoint: "support-tickets",
    detailRoute: (id) => `/tickets/${id}`,
    search: "Search ticket, UID or subject…",
    columns: [
      { key: "id", label: "Ticket", mono: true },
      { key: "uid", label: "User UID", mono: true },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status", badge: true },
      { key: "createdAt", label: "Created", type: "datetime" },
    ],
    filters: [{ key: "status", label: "Status", options: ["open", "assigned", "resolved", "closed"] }],
    actions: [
      { key: "assign", label: "Assign / reviewing", value: { status: "assigned" } },
      { key: "resolve", label: "Resolve" },
      { key: "close", label: "Close" },
    ],
  },
  subscriptions: {
    title: "Subscriptions",
    subtitle: "Users with an active plan / tier",
    endpoint: "subscriptions",
    search: "Search user…",
    columns: [
      { key: "uid", label: "User UID", mono: true },
      { key: "displayName", label: "Name" },
      { key: "tier", label: "Tier", badge: true },
      { key: "subTier", label: "Sub Tier" },
      { key: "subscriptionPlan", label: "Plan" },
      { key: "subscriptionStatus", label: "Status", badge: true },
      { key: "country", label: "Country" },
    ],
    filters: [],
    actions: [],
  },
};
