"""Starter content pools for the Play Together games.

Genuine, playable content (English, language='en'). Admins expand/edit via the
Content Manager without code changes. Item shapes match the engine contracts:
  choice/trivia : {id, prompt, options:[{key,label}], correct?(trivia), tags}
  prompt        : {id, prompt, mode:'each'|'turn'}
  guess         : {id, prompt, options?} | kind:'truths_lie'
  coop          : {id, prompt, options?}
"""

def _opts(*labels):
    return [{"key": chr(97 + i), "label": l} for i, l in enumerate(labels)]


def _c(prompt, *labels, tags=None):
    return {"prompt": prompt, "options": _opts(*labels), "tags": tags or []}


def _t(prompt, options, correct, tags=None):
    return {"prompt": prompt, "options": _opts(*options), "correct": correct, "tags": tags or []}


def _p(prompt, mode="each"):
    return {"prompt": prompt, "mode": mode}


CONTENT = {
    # ---------------- CHOICE pools ----------------
    "would_you_rather": [
        _c("Would you rather…", "Be able to fly", "Be invisible"),
        _c("Would you rather…", "Always be 10 minutes late", "Always be 20 minutes early"),
        _c("Would you rather…", "Explore space", "Explore the deep ocean"),
        _c("Would you rather…", "Have unlimited books", "Have unlimited movies"),
        _c("Would you rather…", "Live by the beach", "Live in the mountains"),
        _c("Would you rather…", "Read minds", "See the future"),
        _c("Would you rather…", "Never use social media again", "Never watch TV again"),
        _c("Would you rather…", "Travel to the past", "Travel to the future"),
        _c("Would you rather…", "Be a famous singer", "Be a famous actor"),
        _c("Would you rather…", "Have a personal chef", "Have a personal driver"),
        _c("Would you rather…", "Always speak your mind", "Never speak again"),
        _c("Would you rather…", "Give up coffee forever", "Give up dessert forever"),
        _c("Would you rather…", "Have more time", "Have more money"),
        _c("Would you rather…", "Own a dragon", "Be a dragon"),
        _c("Would you rather…", "Only whisper", "Only shout"),
    ],
    "this_or_that": [
        _c("Pick one", "Coffee", "Tea"), _c("Pick one", "Morning", "Night"),
        _c("Pick one", "Sweet", "Savoury"), _c("Pick one", "Cats", "Dogs"),
        _c("Pick one", "City", "Countryside"), _c("Pick one", "Call", "Text"),
        _c("Pick one", "Summer", "Winter"), _c("Pick one", "Books", "Movies"),
        _c("Pick one", "Adventure", "Relaxation"), _c("Pick one", "Pizza", "Burgers"),
        _c("Pick one", "Early bird", "Night owl"), _c("Pick one", "Plan", "Spontaneity"),
        _c("Pick one", "Sunrise", "Sunset"), _c("Pick one", "Music", "Podcasts"),
        _c("Pick one", "Window seat", "Aisle seat"),
    ],
    "personality": [
        _c("At a party you are more likely to…", "Start conversations", "Wait to be approached"),
        _c("You make decisions with your…", "Head", "Heart"),
        _c("You'd rather spend a free evening…", "Out with friends", "Cosy at home"),
        _c("You handle stress by…", "Talking it out", "Taking space"),
        _c("You're more…", "Spontaneous", "Organised"),
        _c("You prefer to…", "Lead", "Support"),
        _c("Your ideal weekend is…", "Packed with plans", "Totally open"),
        _c("You value more…", "Honesty", "Kindness"),
        _c("You learn best by…", "Doing", "Watching"),
        _c("You recharge by…", "Being social", "Being alone"),
        _c("You're drawn to…", "Big ideas", "Small details"),
        _c("You'd describe yourself as…", "Optimist", "Realist"),
    ],
    "emoji_personality": [
        _c("Pick the emoji that fits your mood", "😄", "😌", "🔥", "🌧️"),
        _c("Your energy right now", "⚡", "🌊", "🌙", "☀️"),
        _c("How you love", "❤️", "🫶", "💌", "🌹"),
        _c("Your weekend vibe", "🎉", "🛋️", "🏔️", "📚"),
        _c("Your spirit animal", "🦁", "🐬", "🦉", "🐢"),
        _c("Your comfort food mood", "🍕", "🍫", "🍜", "🍓"),
        _c("Your travel style", "🎒", "🧳", "🏝️", "🗺️"),
        _c("Your friendship style", "🤗", "😂", "🧠", "🛡️"),
        _c("Your dream setting", "🌆", "🌲", "🏖️", "🏰"),
        _c("Your motto", "✨", "💪", "🧘", "🎯"),
    ],
    "mood": [
        _c("Right now I feel…", "Energetic", "Calm", "Playful", "Thoughtful"),
        _c("Tonight I want…", "Adventure", "Comfort", "Laughter", "Quiet"),
        _c("My ideal music now…", "Upbeat", "Chill", "Romantic", "None"),
        _c("I could go for…", "A walk", "A nap", "A chat", "A snack"),
        _c("My social battery is…", "Full", "Half", "Low", "Recharging"),
        _c("I'm craving…", "Something sweet", "Something spicy", "Something salty", "Nothing"),
        _c("My focus is…", "Sharp", "Wandering", "Relaxed", "Sleepy"),
        _c("Weather I'd pick now…", "Sunny", "Rainy", "Snowy", "Breezy"),
        _c("My vibe word…", "Cosy", "Wild", "Curious", "Peaceful"),
        _c("I'd rather…", "Talk", "Listen", "Play", "Rest"),
    ],
    "what_would_you_do": [
        _c("You find a wallet with cash on the street. You…", "Hand it to police", "Try to find the owner online", "Leave it", "Take it to a shop nearby"),
        _c("You win a free holiday for two. You take…", "Your best friend", "Your partner", "A family member", "Go solo"),
        _c("A stranger needs directions but you're late. You…", "Stop and help", "Quickly point the way", "Apologise and rush", "Call someone to help them"),
        _c("You get an extra day off tomorrow. You…", "Sleep in", "Plan a trip", "Catch up on hobbies", "See friends"),
        _c("You find £100 you forgot about. You…", "Save it", "Treat yourself", "Gift someone", "Donate it"),
        _c("Your friend is upset. You…", "Listen quietly", "Offer advice", "Distract them with fun", "Give them space"),
        _c("You could master one skill instantly. You choose…", "A language", "An instrument", "Cooking", "Coding"),
        _c("It starts raining on your picnic. You…", "Move indoors", "Embrace it", "Pack up and go home", "Wait it out"),
        _c("You're offered your dream job in another city. You…", "Take it", "Negotiate remote", "Decline to stay", "Ask for time"),
        _c("You have one wish for the world. You wish for…", "Peace", "Health", "Knowledge", "Kindness"),
    ],
    "desert_island": [
        _c("One item on a desert island", "A knife", "A lighter", "A tarp", "A fishing net"),
        _c("One food forever", "Rice", "Potatoes", "Fruit", "Fish"),
        _c("One form of entertainment", "A guitar", "A book of puzzles", "A sketchpad", "A deck of cards"),
        _c("One companion", "A dog", "A close friend", "A survival expert", "A chef"),
        _c("One comfort", "A pillow", "A blanket", "Headphones", "A photo album"),
        _c("One tool", "An axe", "A rope", "A compass", "A first-aid kit"),
        _c("One drink source", "A water filter", "Coconuts", "A rain catcher", "A well kit"),
        _c("One luxury", "A hammock", "Sunscreen", "A solar charger", "A mirror"),
        _c("One escape plan", "Build a raft", "Signal fire", "Message in a bottle", "Wait for rescue"),
        _c("One skill to have", "Fishing", "Fire-making", "Shelter-building", "Navigation"),
    ],
    "superpower": [
        _c("Which power?", "Flight", "Invisibility", "Super strength", "Teleportation"),
        _c("Which power?", "Time travel", "Mind reading", "Healing", "Telekinesis"),
        _c("Which power?", "Talk to animals", "Breathe underwater", "Super speed", "Shape-shifting"),
        _c("Which power?", "Control weather", "Freeze time", "See the future", "Duplicate yourself"),
        _c("Which power?", "Never need sleep", "Instant learning", "Perfect memory", "Understand any language"),
        _c("Which power?", "Turn invisible", "Walk through walls", "Super hearing", "X-ray vision"),
        _c("Which power?", "Summon food", "Summon money", "Summon friends", "Summon calm"),
        _c("Which power?", "Fireproof", "Bulletproof", "Weatherproof", "Fearless"),
        _c("Which power?", "Talk to plants", "Glow in the dark", "Super jump", "Echolocation"),
        _c("Which power?", "Pause the world", "Rewind 10 seconds", "Fast-forward boredom", "Save a moment"),
    ],
    "compatibility": [
        _c("Ideal date", "Dinner out", "Movie night in", "Outdoor adventure", "Something creative"),
        _c("Love language", "Words", "Time", "Gifts", "Acts of service"),
        _c("Weekend together", "Explore a city", "Relax at home", "Try something new", "Visit family/friends"),
        _c("Communication style", "Talk it out now", "Cool off first", "Write it down", "Give a hug"),
        _c("Vacation together", "Beach", "Mountains", "City break", "Road trip"),
        _c("Evening in", "Cook together", "Order in", "Game night", "Movie marathon"),
        _c("Show affection by", "Hugs", "Compliments", "Little gifts", "Helping out"),
        _c("Money style", "Save", "Spend on experiences", "Spend on things", "Split evenly"),
        _c("Conflict repair", "Apologise first", "Give space then talk", "Make a joke", "Do something kind"),
        _c("Future dream", "Travel the world", "Build a home", "Grow a business", "Big family"),
    ],
    "common_ground": [
        _c("Pick a cuisine you'd both enjoy", "Italian", "Indian", "Japanese", "Mexican"),
        _c("A shared hobby to try", "Cooking", "Hiking", "Gaming", "Photography"),
        _c("A genre you both like", "Comedy", "Thriller", "Romance", "Documentary"),
        _c("A holiday you'd both pick", "Beach", "City", "Nature", "Cruise"),
        _c("A night out together", "Live music", "Dinner", "Bowling", "Comedy club"),
        _c("A pet you'd both want", "Dog", "Cat", "Fish", "None"),
        _c("A drink you'd both order", "Coffee", "Tea", "Smoothie", "Water"),
        _c("A weekend activity", "Market", "Museum", "Park", "Cinema"),
        _c("Music for a road trip", "Pop", "Rock", "Hip-hop", "Classics"),
        _c("A takeaway you'd share", "Pizza", "Sushi", "Burgers", "Noodles"),
    ],

    # ---------------- statement pools (choice with You/Them/Both/Neither) ----------------
    "most_likely_statements": [
        _c("Most likely to send a good-morning text", "You", "Them", "Both", "Neither"),
        _c("Most likely to plan a surprise", "You", "Them", "Both", "Neither"),
        _c("Most likely to laugh at their own joke", "You", "Them", "Both", "Neither"),
        _c("Most likely to try a new restaurant", "You", "Them", "Both", "Neither"),
        _c("Most likely to get lost with no map", "You", "Them", "Both", "Neither"),
        _c("Most likely to stay up too late", "You", "Them", "Both", "Neither"),
        _c("Most likely to forget a password", "You", "Them", "Both", "Neither"),
        _c("Most likely to sing in the shower", "You", "Them", "Both", "Neither"),
        _c("Most likely to win a dance-off", "You", "Them", "Both", "Neither"),
        _c("Most likely to cry at a movie", "You", "Them", "Both", "Neither"),
        _c("Most likely to become famous", "You", "Them", "Both", "Neither"),
        _c("Most likely to adopt ten pets", "You", "Them", "Both", "Neither"),
    ],

    # ---------------- PROMPT pools ----------------
    "quick_questions": [
        _p("What's your go-to comfort food?"), _p("What's a small thing that made you smile today?"),
        _p("Beach or mountains — and why?"), _p("What's your favourite way to relax?"),
        _p("What song is stuck in your head?"), _p("What's your dream travel destination?"),
        _p("Tea, coffee, or something else?"), _p("What's a hobby you'd love to pick up?"),
        _p("Early bird or night owl?"), _p("What's your favourite season?"),
        _p("What's the last thing that made you laugh?"), _p("What's your ideal Sunday?"),
        _p("Sweet or savoury snacks?"), _p("What's a movie you can rewatch forever?"),
        _p("What's your hidden talent?"),
    ],
    "conversation_cards": [
        _p("What's a memory that always makes you happy?"),
        _p("If you could have dinner with anyone, who would it be?"),
        _p("What's something you're proud of but rarely mention?"),
        _p("What does a perfect day look like for you?"),
        _p("What's a lesson life taught you the hard way?"),
        _p("What's a dream you haven't given up on?"),
        _p("Who has influenced you the most?"),
        _p("What's something new you'd love to learn?"),
        _p("What place feels most like home to you?"),
        _p("What's a small act of kindness you'll never forget?"),
        _p("What makes you feel truly relaxed?"),
        _p("What's your idea of a great friendship?"),
    ],
    "get_to_know_me": [
        _p("Where did you grow up, and what was it like?"),
        _p("What do you do for fun on a typical week?"),
        _p("What's your favourite way to spend money?"),
        _p("What's a goal you're working towards right now?"),
        _p("What kind of music do you love?"),
        _p("Are you more of a planner or a go-with-the-flow person?"),
        _p("What's your favourite meal to cook or eat?"),
        _p("What's something you're passionate about?"),
        _p("How do you like to celebrate your birthday?"),
        _p("What's a book, show, or film that changed your view?"),
        _p("What are you most grateful for lately?"),
        _p("What's your ideal weekend getaway?"),
    ],
    "first_impressions": [
        _p("What's the first thing you notice about someone?"),
        _p("What made you smile in our chat so far?"),
        _p("Describe your vibe in three words."),
        _p("What's a fun fact people wouldn't guess about you?"),
        _p("What do your friends tease you about?"),
        _p("What's your go-to conversation starter?"),
        _p("What kind of energy are you bringing today?"),
        _p("What's a compliment you love receiving?"),
        _p("What's something you're curious about right now?"),
        _p("If today were a colour, what would it be?"),
    ],
    "finish_sentence": [
        _p("Start it: 'The best part of my day is…' — then let them finish.", "turn"),
        _p("Start it: 'If I had a free afternoon, I'd…'", "turn"),
        _p("Start it: 'Something I've always wanted to try is…'", "turn"),
        _p("Start it: 'A perfect meal would be…'", "turn"),
        _p("Start it: 'The song that describes me is…'", "turn"),
        _p("Start it: 'My happy place is…'", "turn"),
        _p("Start it: 'I feel most myself when…'", "turn"),
        _p("Start it: 'A goal for this year is…'", "turn"),
        _p("Start it: 'The kindest thing anyone did for me was…'", "turn"),
        _p("Start it: 'On weekends I love to…'", "turn"),
    ],
    "tell_me_more": [
        _p("Tell me about your favourite place — then we'll go deeper."),
        _p("What's a passion of yours? Tell me how it started."),
        _p("Tell me about someone important to you."),
        _p("What's a challenge you overcame? What did it teach you?"),
        _p("Tell me about a trip you loved — what made it special?"),
        _p("What's a tradition you cherish, and why?"),
        _p("Tell me about a goal — what's your first step?"),
        _p("What's a skill you're proud of? How did you build it?"),
        _p("Tell me about your ideal future — paint the picture."),
        _p("What's something you changed your mind about, and why?"),
    ],
    "never_have_i_ever": [
        _p("Never have I ever… travelled abroad alone. (Share your story!)"),
        _p("Never have I ever… stayed up all night talking."),
        _p("Never have I ever… tried a food I couldn't pronounce."),
        _p("Never have I ever… gone camping in the rain."),
        _p("Never have I ever… learned a dance from a video."),
        _p("Never have I ever… sung karaoke in public."),
        _p("Never have I ever… taken a spontaneous road trip."),
        _p("Never have I ever… cooked a meal from a different country."),
        _p("Never have I ever… run a race or a marathon."),
        _p("Never have I ever… kept a plant alive for a year."),
        _p("Never have I ever… written a poem or a song."),
        _p("Never have I ever… gone a whole day without my phone."),
    ],
    "word_association": [
        _p("Respond with the first word you associate with: OCEAN"),
        _p("First word for: SUMMER"), _p("First word for: MUSIC"),
        _p("First word for: HOME"), _p("First word for: ADVENTURE"),
        _p("First word for: COFFEE"), _p("First word for: NIGHT"),
        _p("First word for: FRIEND"), _p("First word for: CITY"),
        _p("First word for: RAIN"), _p("First word for: GOLD"),
        _p("First word for: JOURNEY"),
    ],
    "category_rush": [
        _p("Name something in the category: FRUITS"),
        _p("Category: COUNTRIES"), _p("Category: ANIMALS"),
        _p("Category: MOVIES"), _p("Category: SPORTS"),
        _p("Category: THINGS IN A KITCHEN"), _p("Category: COLOURS"),
        _p("Category: JOBS"), _p("Category: CITIES"),
        _p("Category: MUSICAL INSTRUMENTS"), _p("Category: BOARD GAMES"),
        _p("Category: THINGS THAT ARE COLD"),
    ],
    "forbidden_word": [
        _p("Describe 'BEACH' without saying: sand, sea, sun."),
        _p("Describe 'PIZZA' without saying: cheese, dough, Italy."),
        _p("Describe 'DOG' without saying: bark, pet, tail."),
        _p("Describe 'RAINBOW' without saying: colour, sky, rain."),
        _p("Describe 'PHONE' without saying: call, text, screen."),
        _p("Describe 'BIRTHDAY' without saying: cake, party, age."),
        _p("Describe 'COFFEE' without saying: drink, hot, morning."),
        _p("Describe 'WINTER' without saying: cold, snow, ice."),
        _p("Describe 'LIBRARY' without saying: books, quiet, read."),
        _p("Describe 'GUITAR' without saying: strings, music, play."),
    ],
    "memory_lane": [
        _p("Share a favourite memory from your childhood."),
        _p("What's a memory that always makes you laugh?"),
        _p("Tell me about a moment you felt truly proud."),
        _p("What's a trip or outing you'll never forget?"),
        _p("Share a memory of someone who shaped who you are."),
        _p("What's a small everyday moment you treasure?"),
        _p("Tell me about a celebration that meant a lot to you."),
        _p("What's a time you surprised yourself?"),
        _p("Share a memory tied to your favourite song."),
        _p("What's a moment of kindness you still remember?"),
    ],
    "couple_challenge": [
        _p("What first drew you to connecting with someone?"),
        _p("What does a caring partner mean to you?"),
        _p("What's your idea of a perfect date night?"),
        _p("How do you like to show you care?"),
        _p("What makes you feel appreciated?"),
        _p("What's a small gesture that melts your heart?"),
        _p("What's something you'd love to do together?"),
        _p("What does trust look like to you?"),
        _p("What's your favourite way to spend a lazy Sunday together?"),
        _p("What's a dream you'd love to share with someone?"),
    ],

    # ---------------- TRIVIA pools ----------------
    "general": [
        _t("How many continents are there?", ["5", "6", "7", "8"], "c"),
        _t("What is the largest planet in our solar system?", ["Earth", "Jupiter", "Saturn", "Mars"], "b"),
        _t("Which gas do plants absorb from the air?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], "c"),
        _t("How many minutes are in a full day?", ["1200", "1440", "1600", "2400"], "b"),
        _t("What is the tallest animal on land?", ["Elephant", "Giraffe", "Horse", "Camel"], "b"),
        _t("Which ocean is the largest?", ["Atlantic", "Indian", "Arctic", "Pacific"], "d"),
        _t("How many colours are in a rainbow?", ["5", "6", "7", "9"], "c"),
        _t("What is frozen water called?", ["Steam", "Ice", "Mist", "Cloud"], "b"),
        _t("Which is a primary colour?", ["Green", "Orange", "Blue", "Purple"], "c"),
        _t("How many legs does a spider have?", ["6", "8", "10", "12"], "b"),
        _t("What do bees make?", ["Milk", "Silk", "Honey", "Wax only"], "c"),
        _t("Which planet is known as the Red Planet?", ["Venus", "Mars", "Mercury", "Neptune"], "b"),
    ],
    "movie": [
        _t("In which film would you find a character named Woody the cowboy?", ["Shrek", "Toy Story", "Cars", "Up"], "b"),
        _t("Which film features a young wizard at a school of magic?", ["Harry Potter", "Twilight", "Narnia", "Matrix"], "a"),
        _t("What kind of animal is Simba?", ["Tiger", "Lion", "Leopard", "Cheetah"], "b"),
        _t("Which movie is about toys that come to life?", ["Frozen", "Toy Story", "Moana", "Brave"], "b"),
        _t("In 'Finding Nemo', what type of fish is Nemo?", ["Clownfish", "Goldfish", "Shark", "Tuna"], "a"),
        _t("Which film has a snowman named Olaf?", ["Frozen", "Tangled", "Encanto", "Coco"], "a"),
        _t("What is the name of the ogre in the DreamWorks classic?", ["Donkey", "Shrek", "Puss", "Fiona"], "b"),
        _t("Which movie features a robot left to clean Earth?", ["WALL-E", "Big Hero 6", "Robots", "Iron Giant"], "a"),
        _t("In which film do dinosaurs roam a theme park?", ["King Kong", "Jurassic Park", "Godzilla", "Jaws"], "b"),
        _t("Which animated film is set in the fictional Wakanda-style ocean city?", ["Moana", "Atlantis", "Luca", "Nemo"], "b"),
        _t("Who is the toy space ranger in Toy Story?", ["Buzz Lightyear", "Rex", "Slinky", "Hamm"], "a"),
        _t("Which film features a girl named Elsa with ice powers?", ["Frozen", "Brave", "Tangled", "Wish"], "a"),
    ],
    "music": [
        _t("How many strings does a standard guitar have?", ["4", "5", "6", "7"], "c"),
        _t("Which instrument has black and white keys?", ["Violin", "Piano", "Flute", "Drum"], "b"),
        _t("What do you call a group of musicians playing together?", ["A choir", "A band", "A crowd", "A duet only"], "b"),
        _t("Which instrument is played with a bow?", ["Trumpet", "Violin", "Piano", "Flute"], "b"),
        _t("What is a very slow tempo called?", ["Presto", "Allegro", "Adagio", "Vivace"], "c"),
        _t("How many beats are in a standard 4/4 bar?", ["2", "3", "4", "6"], "c"),
        _t("Which of these is a brass instrument?", ["Clarinet", "Trumpet", "Cello", "Oboe"], "b"),
        _t("What device keeps a steady musical tempo?", ["Metronome", "Tuner", "Amplifier", "Pedal"], "a"),
        _t("A song's main repeated section is called the…", ["Verse", "Bridge", "Chorus", "Intro"], "c"),
        _t("Which instrument is part of the percussion family?", ["Drums", "Flute", "Violin", "Trumpet"], "a"),
        _t("How many keys are on a standard full piano?", ["66", "76", "88", "100"], "c"),
        _t("A high female singing voice is called…", ["Bass", "Tenor", "Soprano", "Baritone"], "c"),
    ],
    "geography": [
        _t("What is the capital of France?", ["Berlin", "Madrid", "Paris", "Rome"], "c"),
        _t("Which is the longest river in the world?", ["Amazon", "Nile", "Yangtze", "Danube"], "b"),
        _t("Mount Everest is located in which mountain range?", ["Andes", "Alps", "Himalayas", "Rockies"], "c"),
        _t("What is the capital of Japan?", ["Seoul", "Beijing", "Tokyo", "Bangkok"], "c"),
        _t("Which country has the most people?", ["USA", "India", "Russia", "Brazil"], "b"),
        _t("The Sahara Desert is on which continent?", ["Asia", "Africa", "Australia", "Europe"], "b"),
        _t("What is the capital of Italy?", ["Milan", "Venice", "Rome", "Naples"], "c"),
        _t("Which ocean lies between Africa and Australia?", ["Atlantic", "Pacific", "Indian", "Arctic"], "c"),
        _t("What is the smallest country in the world?", ["Monaco", "Malta", "Vatican City", "Nauru"], "c"),
        _t("The Great Barrier Reef is off the coast of…", ["Brazil", "Australia", "Mexico", "Thailand"], "b"),
        _t("What is the capital of the United Kingdom?", ["Manchester", "London", "Dublin", "Edinburgh"], "b"),
        _t("Which country is shaped like a boot?", ["Spain", "Greece", "Italy", "Portugal"], "c"),
    ],
    "food": [
        _t("Sushi originally comes from which country?", ["China", "Japan", "Korea", "Thailand"], "b"),
        _t("Which country is famous for pasta and pizza?", ["Greece", "Italy", "Spain", "France"], "b"),
        _t("What spice gives curry its yellow colour?", ["Paprika", "Turmeric", "Cumin", "Saffron only"], "b"),
        _t("Tacos are a traditional dish from…", ["Mexico", "Peru", "Cuba", "Brazil"], "a"),
        _t("Which country is croissants associated with?", ["Italy", "France", "Belgium", "Austria"], "b"),
        _t("What is the main ingredient in hummus?", ["Lentils", "Chickpeas", "Beans", "Peas"], "b"),
        _t("Paella is a famous dish from which country?", ["Spain", "Portugal", "Italy", "Greece"], "a"),
        _t("Which fruit is known as the 'king of fruits' in SE Asia?", ["Mango", "Durian", "Papaya", "Lychee"], "b"),
        _t("What grain is used to make traditional risotto?", ["Wheat", "Rice", "Barley", "Corn"], "b"),
        _t("Kimchi is a fermented dish from…", ["Japan", "China", "Korea", "Vietnam"], "c"),
        _t("Which nut is used to make marzipan?", ["Walnut", "Almond", "Cashew", "Peanut"], "b"),
        _t("Falafel is typically made from…", ["Potatoes", "Chickpeas or fava beans", "Rice", "Corn"], "b"),
    ],
    "science": [
        _t("What planet do we live on?", ["Mars", "Venus", "Earth", "Jupiter"], "c"),
        _t("What is H2O commonly known as?", ["Salt", "Water", "Oxygen", "Acid"], "b"),
        _t("What force pulls objects toward Earth?", ["Magnetism", "Gravity", "Friction", "Tension"], "b"),
        _t("How many bones are in the adult human body?", ["106", "206", "306", "406"], "b"),
        _t("What do we call animals that eat only plants?", ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], "b"),
        _t("What is the powerhouse of the cell?", ["Nucleus", "Mitochondria", "Ribosome", "Membrane"], "b"),
        _t("Which planet is closest to the Sun?", ["Venus", "Earth", "Mercury", "Mars"], "c"),
        _t("What gas do humans need to breathe?", ["Nitrogen", "Oxygen", "Helium", "Carbon dioxide"], "b"),
        _t("What is the speed of light approximately?", ["300 km/s", "3,000 km/s", "300,000 km/s", "30 km/s"], "c"),
        _t("What state of matter is steam?", ["Solid", "Liquid", "Gas", "Plasma"], "c"),
        _t("Which vitamin does sunlight help produce?", ["A", "B12", "C", "D"], "d"),
        _t("What organ pumps blood around the body?", ["Lungs", "Heart", "Liver", "Kidney"], "b"),
    ],
    "technology": [
        _t("What does 'www' stand for?", ["World Wide Web", "Wide Web World", "Web World Wide", "World Web Wide"], "a"),
        _t("What company makes the iPhone?", ["Google", "Apple", "Samsung", "Sony"], "b"),
        _t("What does 'CPU' stand for?", ["Central Processing Unit", "Computer Power Unit", "Central Power Utility", "Core Processing Unit"], "a"),
        _t("Which of these is a web browser?", ["Photoshop", "Chrome", "Excel", "Slack"], "b"),
        _t("What does 'GPS' help you do?", ["Cook", "Navigate", "Type", "Charge"], "b"),
        _t("Which company created Android?", ["Apple", "Microsoft", "Google", "Nokia"], "c"),
        _t("What does 'RAM' stand for?", ["Read Access Memory", "Random Access Memory", "Rapid App Memory", "Run And Manage"], "b"),
        _t("What symbol starts most email handles?", ["#", "@", "&", "%"], "b"),
        _t("What does 'AI' stand for?", ["Auto Input", "Artificial Intelligence", "Applied Internet", "Active Interface"], "b"),
        _t("Which is a programming language?", ["Python", "Cobra", "Viper", "Lizard"], "a"),
        _t("What stores data in the 'cloud'?", ["Local disk only", "Remote servers", "The screen", "The keyboard"], "b"),
        _t("What does 'USB' commonly connect?", ["Devices", "Rivers", "Roads", "People"], "a"),
    ],
    "history": [
        _t("The Great Wall is located in which country?", ["Japan", "China", "India", "Korea"], "b"),
        _t("Who was the first person on the Moon?", ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], "c"),
        _t("The pyramids of Giza are in which country?", ["Mexico", "Egypt", "Sudan", "Iraq"], "b"),
        _t("In which country did the Olympic Games begin?", ["Italy", "Greece", "Egypt", "Turkey"], "b"),
        _t("Who painted the Mona Lisa?", ["Michelangelo", "Da Vinci", "Van Gogh", "Picasso"], "b"),
        _t("The Titanic sank in which year (century)?", ["1800s", "Early 1900s", "1950s", "1980s"], "b"),
        _t("Which ancient civilisation built Machu Picchu?", ["Maya", "Aztec", "Inca", "Roman"], "c"),
        _t("The Colosseum is found in which city?", ["Athens", "Rome", "Cairo", "Istanbul"], "b"),
        _t("Who is known for the theory of gravity via a falling apple?", ["Einstein", "Newton", "Galileo", "Darwin"], "b"),
        _t("Which country gifted the Statue of Liberty to the USA?", ["Britain", "France", "Spain", "Italy"], "b"),
        _t("Hieroglyphics were a writing system of which people?", ["Romans", "Greeks", "Egyptians", "Vikings"], "c"),
        _t("The first modern telephone is credited to…", ["Edison", "Bell", "Tesla", "Marconi"], "b"),
    ],
    "guess_fact": [
        _t("Which statement is TRUE?", ["Bananas grow underground", "Honey never spoils", "Fish can't swim backwards ever", "The Sun is a planet"], "b"),
        _t("Which is TRUE?", ["Octopuses have three hearts", "Spiders have four legs", "Bats are blind", "Sharks are mammals"], "a"),
        _t("Which is TRUE?", ["Lightning never strikes twice", "The Eiffel Tower can grow taller in heat", "Goldfish have 3-second memory", "Humans use 10% of their brains"], "b"),
        _t("Which is TRUE?", ["A group of flamingos is a 'flamboyance'", "Penguins can fly", "Camels store water in humps", "Ostriches bury their heads"], "a"),
        _t("Which is TRUE?", ["Water boils faster with salt only", "Honey is made by bees from nectar", "Diamonds are the softest gem", "The Moon makes its own light"], "b"),
        _t("Which is TRUE?", ["Tomatoes are botanically fruits", "Carrots are always orange in nature", "Peanuts are true nuts", "Rice grows without water"], "a"),
        _t("Which is TRUE?", ["Sound travels faster in water than air", "Sound cannot travel in water", "Sound is fastest in a vacuum", "Sound needs light to travel"], "a"),
        _t("Which is TRUE?", ["The heart stops when you sneeze", "Your stomach gets a new lining regularly", "Hair keeps growing after we die", "You swallow 8 spiders a year"], "b"),
        _t("Which is TRUE?", ["Mercury is the hottest planet", "Venus is the hottest planet", "Mars is the hottest planet", "Saturn is the hottest planet"], "b"),
        _t("Which is TRUE?", ["A day on Venus is longer than its year", "A day on Earth is 30 hours", "The Sun orbits Earth", "Stars are cold"], "a"),
    ],
    "true_false": [
        _t("The Pacific is the largest ocean.", ["True", "False"], "a"),
        _t("Humans have four lungs.", ["True", "False"], "b"),
        _t("A triangle has three sides.", ["True", "False"], "a"),
        _t("The Sun rises in the west.", ["True", "False"], "b"),
        _t("Spiders are insects.", ["True", "False"], "b"),
        _t("Water freezes at 0°C.", ["True", "False"], "a"),
        _t("There are 12 months in a year.", ["True", "False"], "a"),
        _t("Bats are birds.", ["True", "False"], "b"),
        _t("The Great Wall of China is in Japan.", ["True", "False"], "b"),
        _t("Honey is made by bees.", ["True", "False"], "a"),
        _t("A week has eight days.", ["True", "False"], "b"),
        _t("Mount Everest is the tallest mountain above sea level.", ["True", "False"], "a"),
    ],
    "guess_word": [
        _t("Clue: A yellow fruit monkeys love.", ["Apple", "Banana", "Grape", "Cherry"], "b"),
        _t("Clue: Frozen water that falls in winter.", ["Rain", "Snow", "Hail only", "Mist"], "b"),
        _t("Clue: A large grey animal with a trunk.", ["Rhino", "Elephant", "Hippo", "Bear"], "b"),
        _t("Clue: You read it and it has many pages.", ["Pen", "Book", "Map", "Cup"], "b"),
        _t("Clue: It tells the time on your wrist.", ["Ring", "Watch", "Band", "Clock tower"], "b"),
        _t("Clue: A vehicle that flies with wings.", ["Boat", "Train", "Aeroplane", "Car"], "c"),
        _t("Clue: The star at the centre of our system.", ["Moon", "Sun", "Mars", "Comet"], "b"),
        _t("Clue: A place with many books to borrow.", ["Bakery", "Library", "Gallery", "Pharmacy"], "b"),
        _t("Clue: A season of falling leaves.", ["Spring", "Autumn", "Summer", "Winter"], "b"),
        _t("Clue: A drink made from roasted beans.", ["Tea", "Coffee", "Juice", "Milk"], "b"),
    ],
    "word_scramble": [
        _t("Unscramble: 'PPALE'", ["Apple", "Ample", "Plead", "Paleo"], "a"),
        _t("Unscramble: 'CEANO'", ["Canoe", "Ocean", "Dance", "Cameo"], "b"),
        _t("Unscramble: 'GITER'", ["Grite", "Tiger", "Trige", "Giter"], "b"),
        _t("Unscramble: 'SUEHO'", ["House", "Hoseu", "Shoue", "Ehous"], "a"),
        _t("Unscramble: 'NEGRE'", ["Genre", "Green", "Reneg", "Neger"], "b"),
        _t("Unscramble: 'RSTAE'", ["Stare", "Tears", "Rates", "Aster"], "a"),
        _t("Unscramble: 'NOMO'", ["Mono", "Moon", "Noom", "Onom"], "b"),
        _t("Unscramble: 'CIMSU'", ["Music", "Sumic", "Mucis", "Cumis"], "a"),
        _t("Unscramble: 'DFRINE'", ["Finder", "Friend", "Fdrine", "Rinfed"], "b"),
        _t("Unscramble: 'RLDOW'", ["Dowlr", "World", "Wordl", "Rowld"], "b"),
    ],
    "missing_letters": [
        _t("Complete: EL_PH_NT", ["EF/E", "E/A", "O/A", "E/O"], "b"),
        _t("Complete: B_N_NA", ["A/A", "O/A", "A/O", "E/A"], "a"),
        _t("Complete: C_MP_TER", ["O/U", "A/U", "O/E", "U/O"], "a"),
        _t("Complete: MO_NT_IN", ["U/A", "O/A", "U/E", "A/A"], "a"),
        _t("Complete: R_INB_W", ["A/O", "E/O", "A/U", "O/O"], "a"),
        _t("Complete: BUT_ER_LY", ["T/F", "T/T", "F/F", "D/F"], "a"),
        _t("Complete: CH_C_LATE", ["O/O", "A/O", "O/A", "U/O"], "a"),
        _t("Complete: UM_R_LLA", ["B/E", "B/A", "P/E", "B/O"], "a"),
        _t("Complete: DIN_S_UR", ["O/A", "A/O", "O/O", "E/A"], "a"),
        _t("Complete: KE_BO_RD", ["Y/A", "Y/O", "I/A", "Y/E"], "a"),
    ],
    "riddle": [
        _t("What has keys but can't open locks?", ["A map", "A piano", "A book", "A phone"], "b"),
        _t("What has hands but cannot clap?", ["A tree", "A clock", "A glove", "A statue"], "b"),
        _t("What gets wetter the more it dries?", ["A sponge", "A towel", "The sun", "A cloud"], "b"),
        _t("What has a neck but no head?", ["A bottle", "A shirt", "A guitar", "A road"], "a"),
        _t("What has to be broken before you can use it?", ["A door", "An egg", "A window", "A rule"], "b"),
        _t("The more you take, the more you leave behind. What are they?", ["Photos", "Footsteps", "Coins", "Words"], "b"),
        _t("What has many teeth but cannot bite?", ["A saw or comb", "A dog", "A shark", "A zip only"], "a"),
        _t("What goes up but never comes down?", ["A ball", "Your age", "Rain", "A kite"], "b"),
        _t("What has an eye but cannot see?", ["A needle", "A camera", "A potato", "A storm only"], "a"),
        _t("What can travel around the world while staying in a corner?", ["A stamp", "A clock", "A map", "A phone"], "a"),
    ],
    "synonym": [
        _t("A synonym for 'happy' is…", ["Sad", "Joyful", "Tired", "Angry"], "b"),
        _t("A synonym for 'big' is…", ["Large", "Small", "Thin", "Short"], "a"),
        _t("A synonym for 'fast' is…", ["Slow", "Quick", "Calm", "Loud"], "b"),
        _t("A synonym for 'smart' is…", ["Clever", "Weak", "Rude", "Plain"], "a"),
        _t("A synonym for 'brave' is…", ["Fearful", "Bold", "Quiet", "Lazy"], "b"),
        _t("A synonym for 'beautiful' is…", ["Ugly", "Gorgeous", "Dull", "Rough"], "b"),
        _t("A synonym for 'tired' is…", ["Weary", "Alert", "Eager", "Bright"], "a"),
        _t("A synonym for 'begin' is…", ["End", "Start", "Stop", "Pause"], "b"),
        _t("A synonym for 'quiet' is…", ["Loud", "Silent", "Busy", "Harsh"], "b"),
        _t("A synonym for 'rich' is…", ["Poor", "Wealthy", "Cheap", "Broke"], "b"),
    ],
    "opposites": [
        _t("The opposite of 'hot' is…", ["Warm", "Cold", "Mild", "Cool only"], "b"),
        _t("The opposite of 'up' is…", ["Side", "Down", "Over", "Across"], "b"),
        _t("The opposite of 'happy' is…", ["Glad", "Sad", "Calm", "Kind"], "b"),
        _t("The opposite of 'fast' is…", ["Quick", "Slow", "Rapid", "Swift"], "b"),
        _t("The opposite of 'big' is…", ["Huge", "Small", "Tall", "Wide"], "b"),
        _t("The opposite of 'open' is…", ["Shut", "Ajar", "Wide", "Free"], "a"),
        _t("The opposite of 'day' is…", ["Noon", "Night", "Dawn", "Dusk"], "b"),
        _t("The opposite of 'full' is…", ["Empty", "Packed", "Loaded", "Heavy"], "a"),
        _t("The opposite of 'light' is…", ["Bright", "Dark", "Pale", "Clear"], "b"),
        _t("The opposite of 'strong' is…", ["Tough", "Weak", "Firm", "Solid"], "b"),
    ],
    "language_match": [
        _t("Spanish: 'Hola' means…", ["Bye", "Hello", "Please", "Thanks"], "b"),
        _t("French: 'Merci' means…", ["Sorry", "Hello", "Thank you", "Yes"], "c"),
        _t("Italian: 'Ciao' means…", ["Hi/Bye", "Food", "Water", "Friend"], "a"),
        _t("German: 'Danke' means…", ["Please", "Thank you", "Goodbye", "Good"], "b"),
        _t("Japanese: 'Arigato' means…", ["Hello", "Sorry", "Thank you", "Welcome"], "c"),
        _t("Spanish: 'Gracias' means…", ["Please", "Sorry", "Thanks", "Hello"], "c"),
        _t("French: 'Bonjour' means…", ["Good night", "Hello/Good day", "Please", "Sorry"], "b"),
        _t("Hindi: 'Namaste' is a…", ["Food", "Greeting", "Colour", "Number"], "b"),
        _t("Italian: 'Grazie' means…", ["Hello", "Thanks", "Please", "Yes"], "b"),
        _t("German: 'Guten Tag' means…", ["Good night", "Good day", "Goodbye", "Good luck"], "b"),
    ],

    # ---------------- GUESS pools ----------------
    "guess_my_answer": [
        _c("Their favourite: a relaxing evening is…", "A film", "A book", "A walk", "A game"),
        _c("Their pick: dream holiday is…", "Beach", "City", "Mountains", "Cruise"),
        _c("Their choice: morning drink is…", "Coffee", "Tea", "Juice", "Water"),
        _c("Their pick: weekend vibe is…", "Social", "Chill", "Active", "Creative"),
        _c("Their favourite: type of food is…", "Italian", "Indian", "Japanese", "Mexican"),
        _c("Their choice: music genre is…", "Pop", "Rock", "Hip-hop", "Classical"),
        _c("Their pick: pet would be…", "Dog", "Cat", "Fish", "None"),
        _c("Their favourite: season is…", "Spring", "Summer", "Autumn", "Winter"),
        _c("Their choice: night out is…", "Dinner", "Dancing", "Cinema", "Games"),
        _c("Their pick: superpower is…", "Fly", "Invisible", "Teleport", "Read minds"),
    ],
    "how_well": [
        _c("Guess how they'd describe their ideal Sunday", "Lazy", "Active", "Social", "Productive"),
        _c("Guess their comfort food", "Pizza", "Chocolate", "Noodles", "Fruit"),
        _c("Guess their travel style", "Planner", "Spontaneous", "Relaxer", "Explorer"),
        _c("Guess their favourite way to relax", "Music", "Reading", "Walking", "Napping"),
        _c("Guess their go-to drink", "Coffee", "Tea", "Smoothie", "Water"),
        _c("Guess their weekend energy", "High", "Chill", "Balanced", "Depends"),
        _c("Guess their ideal date", "Dinner", "Adventure", "Movie", "Creative"),
        _c("Guess their communication style", "Talker", "Listener", "Texter", "Caller"),
        _c("Guess their dream pet", "Dog", "Cat", "Bird", "None"),
        _c("Guess their happy place", "Beach", "Home", "Nature", "City"),
    ],
    "friendship_challenge": [
        _c("Guess their favourite hangout", "Café", "Park", "Home", "Cinema"),
        _c("Guess their go-to snack", "Crisps", "Chocolate", "Fruit", "Popcorn"),
        _c("Guess their ideal group activity", "Games night", "Dinner", "Trip", "Movie"),
        _c("Guess their favourite emoji", "😂", "❤️", "🔥", "🙌"),
        _c("Guess their best quality (they'd say)", "Loyal", "Funny", "Caring", "Honest"),
        _c("Guess their weekend plan", "Rest", "Explore", "Socialise", "Create"),
        _c("Guess their music for a party", "Pop", "Dance", "Hip-hop", "Throwbacks"),
        _c("Guess their comfort watch", "Comedy", "Drama", "Reality", "Anime"),
        _c("Guess their travel dream", "Roadtrip", "Beach", "City", "Festival"),
        _c("Guess their hidden talent area", "Music", "Art", "Sport", "Cooking"),
    ],
    "two_truths": [
        {"prompt": "Two truths and a lie — about your travels.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your hobbies.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your childhood.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your talents.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your favourite foods.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about places you've lived.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your dreams.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your job or studies.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your family.", "kind": "truths_lie"},
        {"prompt": "Two truths and a lie — about your bucket list.", "kind": "truths_lie"},
    ],

    # ---------------- COOP pools ----------------
    "choose_adventure": [
        _c("You wake up in a mysterious forest. Do you…", "Follow the river", "Climb a tall tree", "Head towards smoke"),
        _c("You reach a fork in the path. Take the…", "Sunny meadow", "Shadowy cave", "Rope bridge"),
        _c("A friendly fox offers help. You…", "Accept and follow", "Politely decline", "Offer it food"),
        _c("Night falls. You decide to…", "Build a shelter", "Keep walking", "Light a signal fire"),
        _c("You find a locked chest. You…", "Search for a key", "Try to pick it", "Leave it be"),
        _c("A storm rolls in. You…", "Take cover", "Push onward", "Find higher ground"),
        _c("You spot a distant village. You…", "Approach openly", "Observe first", "Circle around"),
        _c("The adventure ends. You choose to…", "Return home a hero", "Stay and explore more", "Bring a friend next time"),
    ],
    "dream_trip": [
        _c("Choose the destination", "Tropical island", "European city", "Mountain retreat", "Desert safari"),
        _c("Choose how you travel", "Flight", "Road trip", "Train", "Cruise"),
        _c("Choose the accommodation", "Beach villa", "Boutique hotel", "Cosy cabin", "Camping"),
        _c("Choose a must-do activity", "Local food tour", "Adventure sports", "Museums & culture", "Just relax"),
        _c("Choose the vibe", "Luxury", "Backpacker", "Balanced", "Spontaneous"),
        _c("Choose a day-trip", "Waterfall hike", "City markets", "Boat ride", "Wildlife tour"),
        _c("Choose the soundtrack", "Chill", "Upbeat", "Local music", "No music"),
        _c("Choose a souvenir to bring back", "Photos", "Local craft", "A recipe", "A story"),
    ],
    "perfect_weekend": [
        _c("Friday night starts with…", "Dinner out", "Movie in", "Games night", "Early rest"),
        _c("Saturday morning…", "Lie-in", "Workout", "Farmers market", "Nature walk"),
        _c("Saturday afternoon…", "Explore the city", "Beach time", "A hobby", "Nap & books"),
        _c("Saturday evening…", "Fancy dinner", "Cook together", "Live music", "Stargazing"),
        _c("Sunday morning…", "Brunch", "Yoga", "Sleep in", "Bike ride"),
        _c("Sunday afternoon…", "Museum", "Picnic", "Board games", "Movie marathon"),
        _c("Sunday evening…", "Plan the week", "Relax fully", "Call loved ones", "A quiet walk"),
        _c("Weekend motto…", "Adventure", "Rest", "Connection", "Balance"),
    ],
    "build_story": [
        _p("Start our story with one sentence about a hero and where they live."),
        _p("Add what unexpected event disrupts their day."),
        _p("Add who they meet along the way."),
        _p("Add the challenge they must overcome."),
        _p("Add a surprising twist."),
        _p("Add how they find courage or help."),
        _p("Add the moment things turn around."),
        _p("Add the ending — how does our story close?"),
    ],
    "team_decisions": [
        _c("Team budget for a party — spend most on…", "Food", "Music", "Decorations", "Venue"),
        _c("Planning a trip — priority is…", "Comfort", "Adventure", "Budget", "Relaxation"),
        _c("Choosing a movie for the group…", "Comedy", "Action", "Thriller", "Animation"),
        _c("Dinner as a team — pick…", "Italian", "Asian", "BBQ", "Vegetarian"),
        _c("A team name for us…", "The Dream Team", "Fun Squad", "Game Changers", "The A-Team"),
        _c("Weekend team activity…", "Escape room", "Hiking", "Cooking class", "Bowling"),
        _c("Group holiday vibe…", "Chill", "Party", "Explore", "Wellness"),
        _c("How we make decisions…", "Vote", "Discuss", "Rotate", "Flip a coin"),
    ],
    "bucket_list": [
        _c("Add a dream to our list", "See the Northern Lights", "Learn to surf", "Visit Japan", "Skydive"),
        _c("Add an experience", "Hot air balloon ride", "Road trip coast to coast", "Cook a feast", "Run a 10k"),
        _c("Add a place to visit", "Grand Canyon", "Great Wall", "Santorini", "Safari in Kenya"),
        _c("Add a skill to learn", "Play piano", "Speak a new language", "Photography", "Dancing"),
        _c("Add an act of kindness", "Volunteer", "Plant trees", "Mentor someone", "Random gift"),
        _c("Add a challenge", "Hike a mountain", "Digital detox week", "Read 12 books", "Try 30 new foods"),
        _c("Add a cosy dream", "Cabin weekend", "Beach sunrise", "Movie marathon", "Home-cooked feast"),
        _c("Add a bold goal", "Start a project", "Perform on stage", "Travel solo", "Learn to code"),
    ],
}
